on:
  push:
    branches:
    - main
    - release/*

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api:
    name: build & deploy apps/api
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: use node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: npm install
      run: npm ci

    - name: check if apps/api changed
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
        api_changed=`git diff --name-only HEAD^ HEAD -- apps/api`
        if [ -n "$api_changed" ]; then
          echo "API_CHANGED=true" >> $GITHUB_ENV
          npm run build -w api
        fi
        web_changed=`git diff --name-only HEAD^ HEAD -- apps/web`
        if [ -n "$web_changed" ]; then
          echo "WEB_CHANGED=true" >> $GITHUB_ENV
          npm run build -w web
        fi


    - name: check if apps/web changed
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        npm run build -w web -w api
        echo "API_CHANGED=true" >> $GITHUB_ENV
        echo "WEB_CHANGED=true" >> $GITHUB_ENV


    - name: deploy api
      if: ${{ env.API_CHANGED != '' }}
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAMER }}
        key: ${{ secrets.KEY }}
        source: "apps/api/dist,apps/api/package.json"
        target: ${{ secrets.API_TARGET }}
        strip_components: 2

    - name: Setup Pages
      if: ${{ env.WEB_CHANGED != '' }}
      uses: actions/configure-pages@v3

    - name: Upload artifact
      if: ${{ env.WEB_CHANGED != '' }}
      uses: actions/upload-pages-artifact@v1
      with:
        path: './apps/web/dist'

    - name: Deploy to GitHub Pages
      if: ${{ env.WEB_CHANGED != '' }}
      id: deployment
      uses: actions/deploy-pages@v1
