on:
  push:
    branches:
    - main
    - release/*
jobs:
  build:
    name: build the repo
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout the repo
      uses: actions/checkout@v3
    - name: use node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: npm install, build, deploy
      run: |
        npm install
        npm run build -w web --if-present
  deploy:
    name: deploy to github pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.4
        with:
          # Should this action only emit build telemetry instead of deploying the build artifact?
          emit_telemetry: false # optional, default is false
          # The status of the previous build.
          conclusion: false # optional
          # GitHub token
          token: ${{ github.token }} # default is ${{ github.token }}
          # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
          timeout: 600000 # optional, default is 600000
          # Maximum number of status report errors before cancelling a deployment (default: 10)
          error_count: 0 # optional, default is 10
          # Time in milliseconds between two deployment status report (default: 5 seconds)
          reporting_interval: 5000 # optional, default is 5000
          # Name of the artifact to deploy
          artifact_name: github-pages # optional, default is github-pages
          # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
          preview: false # optional, default is false
