on:
  push:
    branches:
    - main
    - release/*
jobs:
  build:
    name: build the repo
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout the repo
      uses: actions/checkout@v1
    - name: use node.js v18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: npm install, build, deploy
      run: |
        npm install
        npm run build --if-present
        npm run deploy --if-present
